### ISSUE TITLE
Addditional check: share object values in interests

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#112]
This is a bit of a minefield. I've tried to rationalise what tests we do.

#### Check 1:
That in each interest object in a Relationship statement, if a value for share.exact exists, then no values exist for share.exclusiveMinimum, share.minimum, share.maximum, or share.exclusiveMaximum.

On fail:
- Error message: This Relationship statement contains an interest whose share value is exact. No minimum or maximum value should also be given.  
- Info message: Interest share (share.exact): [VALUE]

On pass:
- Run check 2

#### Check 2:

That in each interest object in a Relationship statement, if both the following exist:

(a) EITHER a value for share.exclusiveMinimum OR a value for share.minimum (not both)  and
(b) EITHER a value for share.maximum OR a value for share.exclusiveMaximum (not both).

Then assign value (a) to minVal, and assign value (b) to maxVal. 

Check that maxVal >= minVal

On fail:
- Error message: This Relationship statement contains an interest whose share falls into a badly described range. The maximum value is less than the minimum value.
- Info message: (Exclusive)minimum value: [minVal], (Exclusive)maximum value: [maxVal]

On pass:
- Run check 3

#### Check 3:

That maxVal != minVal

On fail:
- Error message: This Relationship statement contains an interest whose share proportion is badly described. The (exclusive)maximum value is the same as the (exclusive)minimum value.
- Info message: (Exclusive)minimum value: [minVal], (Exclusive)maximum value: [maxVal]

**Comment by kathryn-ods** [comment]
wondering if there's a case where we might allow minimum=maximum? This would effectively be the same as having an exact value as these are both inclusive. Maybe there's a scenario where that would make sense in some cases? Will proceed as that not being allowed but noting as a thought here.
