### ISSUE TITLE
data quality for address

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/lib-cove-bods#16]
Moving @kd-ods spec to GH.

Under an 'Address quality' subheading:

Report the number of address objects in the dataset
Report the percentage of addresses that have a non-empty postcode field
Report the percentage of addresses that have a non-empty country code field
Report the percentage of addresses where a non-empty string in the postcode field is replicated in the Address field

**Comment by odscjames** [comment]
I'm assuming this is address objects under the "addresses" array key AND the "placeOfResidence" and "placeOfBirth"  keys?

**Comment by kd-ods** [comment]
Yes - and there's the 'addresses' key in entityStatement too.

**Comment by odscjames** [comment]
> Report the percentage of addresses where a non-empty string in the postcode field is replicated in the Address field

Done case sensitive - maybe should be case in-sensitive?

**Comment by odscjames** [comment]
> Yes - and there's the 'addresses' key in entityStatement too.

Got that.

**Comment by kd-ods** [comment]
Yes - case insensitive is probably best.
