### ISSUE TITLE
Requirements.txt needs editing

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#19]
Add 

-e .

**Comment by odscjames** [comment]
That is in req.in. 

What's the problem we are trying to solve here?

**Comment by kd-ods** [comment]
James, you were troubleshooting my running this locally (a few weeks ago) and this was what came out of it. Someone must have fixed the requirements.txt file subsequently?

**Comment by odscjames** [comment]
Oh yes, that rings a bell now. But I can't remember the details, and "-e ." has been there for 4 months. Hmmmm. We might have to check on your laptop again (delete and recreate virtualenv) and see if there is still a problem.

**Comment by odscjames** [comment]
I've worked out why we need to do this; because the libcovebods cli command won't work if you don't. Ok, I'll look at that.

**Comment by Bjwebb** [comment]
Removed requirements.txt in favour of setup.py. New installation instructions https://github.com/openownership/lib-cove-bods/#installation
