### ISSUE TITLE
New validation check: address types should match descriptions in schema

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/lib-cove-bods#22]
To spec properly later but:

- some address types are only associated with natural persons;
- some address types are only associated with legal entities;
- addresses with type alternative must be accompanied with another primary address.

**Comment by kd-ods** [comment]
Here's the spec. We need to validate that:

- If Address.type is 'placeOfBirth', 'residence', or 'service', then the parent statement is a Person Statement.

- if Address.type is 'registered', or 'business' then the parent statement is an Entity Statement.

- if Address.type is 'alternative' then the parent Statement contains at least one other Address object with type not 'alternative'.

**Comment by odscjames** [comment]
It looks like this should only be checked on 0.2 data?

**Comment by kd-ods** [comment]
Yes, this only needs to be checked for 0.2.

**Comment by odscjames** [comment]
Having read the draft spec carefully, I think I'm safe in rewriting the first two points to:

*  A person statement should only have addresses of type  'placeOfBirth', 'residence', or 'service', or 'alternative' 

* A Entity statement should only have addresses of type 'registered', or 'business' or  'alternative' 

* Third point as above

**Comment by odscjames** [comment]
![issue22a](https://user-images.githubusercontent.com/37832009/61181510-af7e5580-a61f-11e9-8e06-e2fe88bcbc26.png)
![issue22b](https://user-images.githubusercontent.com/37832009/61181511-af7e5580-a61f-11e9-9110-6c71e9546d20.png)
![issue22c](https://user-images.githubusercontent.com/37832009/61181512-b016ec00-a61f-11e9-9c46-cc4c517842ae.png)
![issue22d](https://user-images.githubusercontent.com/37832009/61181513-b016ec00-a61f-11e9-994f-ca7fa121be60.png)

Ok?

**Comment by kd-ods** [comment]
Looks good. I'll leave you to close it @odscjames

**Comment by odscjames** [comment]
This has now been merged to master in cove and is just waiting for a deploy.
