### ISSUE TITLE
New validation check: isComponent part 1

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#23]
If an entity, person or ooc statement has isComponent value ‘true’ check that there is a primary ooc Statement which references it (by statementID) from the primary’s componentStatementIDs property.

**Comment by odscjames** [comment]
To expand the definition a bit to be clear about primary ooc:

If an entity, person or ooc statement has isComponent value ‘true’ check that there is another ooc Statement **with isComponent value ‘false’** which references it (by statementID) from the componentStatementIDs property.

And to add part 2 from https://github.com/openownership/lib-cove-bods/issues/24

If an entity, person or ooc statement has isComponent value ‘true’ check that there is another ooc Statement **later in the document** with isComponent value ‘false’ which references it (by statementID) from the componentStatementIDs property.

**Comment by kd-ods** [comment]
OK, so we def want 'part 2' from #24 to be a separate check. So we want this part 1 check to be:

If an entity, person or ooc statement has isComponent value ‘true’ check that there is another ooc Statement **later in the document** which references it (by statementID) from the componentStatementIDs property.

And check later (part 2) that that primary ooc statement has isComponent value 'false.

**Comment by odscjames** [comment]
> And check later (part 2) that that primary ooc statement has isComponent value 'false.

I'm confused - I thought #24 was about ordering? I think I'm not clear what you mean about primary statement - that was what I was trying to define clearly with my first rewrite.

**Comment by odscjames** [comment]
Ok, so #23 and #24 should be separate checks.

This check should be:

If an entity, person or ooc statement has isComponent value ‘true’ check that there is another ooc Statement with isComponent value ‘false’ which references it (by statementID) from the componentStatementIDs property.

@kd-ods you highlighted "later in the document" but is that not dealt with in #24? And "And check later (part 2) that that primary ooc statement has isComponent value 'false."" - Is that not #26 not #24?

**Comment by kd-ods** [comment]
Yes. We think it's more informative to keep #23 and #24 as separate checks.

**Comment by odscjames** [comment]
![issue23](https://user-images.githubusercontent.com/37832009/61181808-eefa7100-a622-11e9-9841-1bf597999f0c.png)


Ok?

**Comment by odscjames** [comment]
![issue23](https://user-images.githubusercontent.com/37832009/61181819-15b8a780-a623-11e9-9109-020b43309e01.png)

Ok? 

Not sure if we should cover the "primary" check in there somewhere?

**Comment by kd-ods** [comment]
Please rephrase to "This Ownership-or-control Statement is a component (isComponent) but no primary Ownership-or-control Statement references it (from componentStatementIDs)".

**Comment by odscjames** [comment]
Done

**Comment by odscjames** [comment]
This has now been merged to master in cove and is just waiting for a deploy.
