### ISSUE TITLE
New validation check: isComponent part 2

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#24]
If an entity, person or ooc statement has isComponent value ‘true’ check that the primary ooc Statement appears after the component statement in the BODS package.

**Comment by odscjames** [comment]
Can I rephrase as:

If an entity, person or ooc statement has isComponent value ‘true’ check that there is another ooc Statement **later** in the document which references it (by statementID) from the componentStatementIDs property.

The important part for this check being "later" - the order of statements

**Comment by odscjames** [comment]
See #23 for expanded definition

**Comment by odscjames** [comment]
![issue24](https://user-images.githubusercontent.com/37832009/61181852-911a5900-a623-11e9-968b-bf46f3a7581e.png)

Ok?

Like #23, not sure if we should mention the primary.

**Comment by kd-ods** [comment]
Please rephrase this one as well. To "This Ownership-or-control Statement is a component (isComponent) and should appear **before** the primary Ownership-or-control Statement that references it (from componentStatementIDs)"

**Comment by odscjames** [comment]
Done

**Comment by odscjames** [comment]
This has now been merged to master in cove and is just waiting for a deploy.
