### ISSUE TITLE
New validation check: componentStatementIDs part 2

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#26]
If oocStatement.componentStatementIDs contains any statementIDs, check that oocStatement.isComponent is ‘false’.

**Comment by odscjames** [comment]
Doing this as a check for "any statementIDs" so an empty list is fine.

**Comment by odscjames** [comment]
(The other option is that the componentStatementIDs key just should not exist at all, but you might get some software that writes out a empty list by default maybe)

**Comment by ScatteredInk** [comment]
That sounds fine. We check for minItems in the schema later.

**Comment by odscjames** [comment]
![issue26](https://user-images.githubusercontent.com/37832009/61181721-df2e5d00-a621-11e9-8c44-445bbe2b8fef.png)

Ok?

**Comment by kd-ods** [comment]
Please rephrase to "An Ownership-or-control Statement cannot both be a component statement (isComponent) and have component statements (componentStatementIDs)."

Thanks!

**Comment by odscjames** [comment]
Done

**Comment by odscjames** [comment]
This has now been merged to master in cove and is just waiting for a deploy.
