### ISSUE TITLE
New stat/report: bodsVersion

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#28]
A breakdown of Statement.publicationDetails.bodsVersion. Would give reports like:

_Publication details_

- 236 statements published as BODS v1.0
- 16 statements published as BODS v0.3

**Comment by odscjames** [comment]
#27 says one file can only have statements with the same version. So this report would be simplified?

**Comment by kd-ods** [comment]
Yes - hopefully, the report would have a single line!

**Comment by odscjames** [comment]
This is now in master, ready for release and Cove UI work.

**Comment by odscjames** [comment]
![issue28](https://user-images.githubusercontent.com/37832009/61181426-36323300-a61e-11e9-99d7-3efcf70ee358.png)

Have put at top in new section - we might want to add more later, like check data under different versions or more info on the different versions

**Comment by kd-ods** [comment]
Looks good.

**Comment by odscjames** [comment]
This has now been merged to master in cove and is just waiting for a deploy.

Tho currently it only appears if the data is 0.2 - because 0.2 isn't officially released yet we don't want to show it too much.
