### ISSUE TITLE
New stat/report: hasPepStatus

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#29]
Person Statements with a hasPepStatus value (true or false).

Would give reports like:

Person Statements where PEP status is declared: 235 of 241

**Comment by odscjames** [comment]
![issue29](https://user-images.githubusercontent.com/37832009/61181268-b86d2800-a61b-11e9-9e3e-1fae8ba7d8b3.png)

That ok?

**Comment by kd-ods** [comment]
We should make the reporting on these stats consistent in form. So, since we already have "... with type knownPerson: x (y%)", can we re-word this as:

"...where PEP status is declared: x (y%)"

**Comment by odscjames** [comment]
Done

**Comment by odscjames** [comment]
This has now been merged to master in cove and is just waiting for a deploy.
