### ISSUE TITLE
New stat/report: pepStatusDetails.missingInfoReason

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#30]
Number of Person Statements with a pepStatusDetails.missingInfoReason value which also have a hasPepStatus value.

Would give reports like:

Person Statements which have a reason for missing PEP information but which do declare a PEP status: 2

**Comment by odscjames** [comment]
pepStatusDetails is an array; I'm assuming from the wording of the stat that if ANY (not ALL) of the items in the array have a missingInfoReason then that person should be counted?

**Comment by kd-ods** [comment]
> if ANY (not ALL) of the items in the array have a missingInfoReason then that person should be counted?

Yes.

**Comment by odscjames** [comment]
![issue30](https://user-images.githubusercontent.com/37832009/61181212-ec941900-a61a-11e9-8622-e18d76f6b9e0.png)

This look ok?

**Comment by kd-ods** [comment]
As in #29, we should make the reporting on these stats consistent in form. Here, how about:

"... where PEP status is declared AND (erroneously) a reason for missing PEP information is given: x (y%)"

(And this reported stat should come after that in #29)

**Comment by odscjames** [comment]
Done

**Comment by odscjames** [comment]
This has now been merged to master in cove and is just waiting for a deploy.
