### ISSUE TITLE
New stat/report: Anonymous or missing person reason 

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/lib-cove-bods#31]
Where a personStatement has the type 'anonymousPerson' or 'unknownPerson' a reason for the absence of information SHOULD be provided in `unspecifiedPersonDetails.reason`

**Comment by odscjames** [comment]
It says Stat/Report: Is this a validation alert or a figure about which percentage of person statements with those types do NOT have a reason?

**Comment by kd-ods** [comment]
`reason` has been made required in BODS 0.4.

Closing
