### ISSUE TITLE
In the additional checks table in the UI, how are thing capatalised?

### ISSUE THREAD

**Issue by odscjames** [openownership/lib-cove-bods#35]
Is it:

  *  This Ownership-or-control Statement  ....
  *  This Person Statement ....
  *  This Entity Statement  ....

Note caps and hyphens.

We can make all existing messages consistent if so.

**Comment by ScatteredInk** [comment]
Yes, just had a quick chat about this and that is right - if we could make it all messages consistent that would be great.

**Comment by odscjames** [comment]
Merged to master, live soon
