### ISSUE TITLE
Issues running with libcove 0.19.0

### ISSUE THREAD

**Issue by stevenday** [openownership/lib-cove-bods#61]
I've run into an issue today where my fresh installation of lib-cove-bods 0.8.0 cannot run on the CLI because of a missing `config` attribute on the `SchemaBODS` object. 

It seems `config` was [recently introduced in lib-cove 0.19.0](https://github.com/OpenDataServices/lib-cove/compare/v0.18.0...v0.19.0) and it gets installed because lib-cove-bods [specifies >= 0.18.0 in setup.py](https://github.com/openownership/lib-cove-bods/blob/master/setup.py#L16)

As a temporary workaround I can specify `libcove==0.18.0` in my `requirements.txt` to make sure I get a compatible version, but it seems like we either need to fix the incompatibility or pin the version more strictly. I suspect the latter won't affect anyone, you're only likely to have libcove because of libcovebods, so perhaps that's a good idea anyway?

**Comment by Bjwebb** [comment]
Sorry, I missed that this would break compatibility. The change to lib-cove-bods should be quite straightforward, so I'll take a look over the next few days.

**Comment by Bjwebb** [comment]
There's some more breaking changes in 0.20.0, so my suggestion is we pin for now, see https://github.com/openownership/lib-cove-bods/pull/63
