### ISSUE TITLE
Statistic: breakdown of use of interest.directOrIndirect

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#78]
Under the OOC Statements section > Total Interest Statements, add:

- ... with directOrIndirect 'direct': XX%
- ... with directOrIndirect 'indirect': XX%
- ... with directOrIndirect 'unknown': XX%

(Also, while we're there, can we retitle 'Total Interest Statements' to 'Total Interest objects'.)

**Comment by odscjames** [comment]
> (Also, while we're there, can we retitle 'Total Interest Statements' to 'Total Interest objects'.)

This can apply to all versions - the new stat applies to 0.3 only

**Comment by Blueskies00** [comment]
Tests:
https://docs.google.com/spreadsheets/d/1RCE3PBKXebSfHdgAKZZhOaE3M-4c3pWMpSNcklF-GYg/edit#gid=339537194

20 direct
5 indirect
1 unknown
1 null

Expected result: To see the above represented in the statistics, with associated percentages.
Actual result: All except the null represented.
Comments: The %s presented are accurate based on a total of 27 interest objects. As directOrIndirect isn't actually a required field, depending how many statements show null this could be confusing for an inexperienced user who attempts to calculate the numbers.
Test: PASSED
**ACTIONS: @kd-ods is it worth considering including a stat for nulls when present?**

P.s. this has been done:
>(Also, while we're there, can we retitle 'Total Interest Statements' to 'Total Interest objects'.)
