### ISSUE TITLE
Warning: when no beneficial owners are declared within the data

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#79]
I'm not sure we have the concept of a warning?? If not, then let's add this as an additional check.

We need to throw a warning when no interest objects in the data have `beneficialOwnershipOrControl` set to true. A message like "No individuals are disclosed as beneficial owners. beneficialOwnershipOrControl must be set to true within an Interest object to indicate that the interested party is a beneficial owner."

**Comment by odscjames** [comment]
We already have a stat: "count_ownership_or_control_statement"

How about adding a stat: "count_ownership_or_control_statement_with_at_least_one_interest_beneficial" ?

Then it's simply a matter of how we present it in the UI.

If there are no ownership_or_control statements should this warning still trigger? Or should it only trigger if there are some but none have interests which are beneficial?

**Comment by kd-ods** [comment]
> How about adding a stat: "count_ownership_or_control_statement_with_at_least_one_interest_beneficial" ?

Yes - that's a good idea. How about this for the wording of the stat: "Number of beneficial ownership relations disclosed".

> Then it's simply a matter of how we present it in the UI.

Indeed. I would like that extra warning message (from original post) to display when the stat is 0.

> If there are no ownership_or_control statements should this warning still trigger?

Yes.

**Comment by odscjames** [comment]
I'll apply the stat to all versions of the schema.

Should the warning only show up on 0.3+ tho?

**Comment by odscjames** [comment]
> How about this for the wording of the stat: "Number of beneficial ownership relations disclosed".

Just double checking, if a bit of data has 1 ownership_or_control_statement with 2 interest objects, both beneficial, should it say 1 or 2?

I carefully defined the name so: 1

**Comment by kd-ods** [comment]
>  ...should it say 1 or 2?

Yes - it should say 1.

**Comment by odscjames** [comment]
Had to rephrase the label so it fitted into the "Where" format we use elsewhere.

Let's have a chat about how the warning should appear? eg new box? in stats?

**Comment by Blueskies00** [comment]
Tests:
https://docs.google.com/spreadsheets/d/1RCE3PBKXebSfHdgAKZZhOaE3M-4c3pWMpSNcklF-GYg/edit#gid=339537194

8 OOC statements with at least one beneficialOwnershipOrControl value set to true (even though there are more than 8 TRUE values across the 8 statements).
Expected result: A statistic with a count of 8.
Actual result: As expected.
Comments: Not sure about also representing a % for this stat, but it does no harm.
Test: PASSED
**Actions:** None.

https://docs.google.com/spreadsheets/d/12lXluRHUqiUTIMY0YjzY6JsHF-v_6pURR04hRF7WKFo/edit#gid=339537194
Entity statements only.
Expected result: A statistic with a count of 0, and a warning.
Actual result: No statistic, and no warning anywhere.
Comments: Presumably as the stat was nil, this is why it didn't appear.
Test: FAILED
**Actions: @odscjames @kd-ods I noticed the last comment:**
>Let's have a chat about how the warning should appear? eg new box? in stats?

**Was it decided against a warning appearing somewhere?**

https://docs.google.com/spreadsheets/d/1Ingu-74nvN3tAq1dPb-2B5fqcalkS9pbXl76Gb-YBR0/edit#gid=339537194
Basic complete statement, with the only OOC statement beneficialOwnershipOrControl value set to false.
Expected result: A statistic with a count of 0, and a warning.
Actual result: No statistic, and no warning anywhere.
Comments: Presumably as the stat was nil, this is why it didn't appear.
Test: FAILED
**Actions: As above.**

**Comment by odscjames** [comment]
> Comments: Presumably as the stat was nil, this is why it didn't appear.

Yes, that's the current logic. With that in mind, I'm going to say those 2 tests are actually passes, at least at the data level :-) 

We can tweak UI later if wanted. But this applies to most stats so would want to think carefully.

> Was it decided against a warning appearing somewhere?

Not discussed yet - so currently no warning will appear. For now, we are just making sure the stat is calculated correctly.

**Comment by kd-ods** [comment]
Yes, in the UI we do definitely want a warning appearing if the count of beneficialOwnershipOrControl == true is 0.

As a warning it does need to be fairly prominent. So maybe it could appear at the top of the stats section and in a warning box?

"No individuals are disclosed as beneficial owners. beneficialOwnershipOrControl must be set to true within an Interest object to indicate that the interested party is a beneficial owner."

**Comment by odscjames** [comment]
I've put it as a additional check entry as that's what from the users point of view it is - they don't know/care it is triggered by a stat - comments?

![BODSCHECKSTAT](https://user-images.githubusercontent.com/37832009/176428952-73640811-9086-44d5-9298-8323ec990e9c.png)

We could add something under "Where it occurs" to make clear it applies to all statements and not a single one, as is usually the case? "All statements"

**Comment by kd-ods** [comment]
> We could add something under "Where it occurs" to make clear it applies to all statements and not a single one, as is usually the case? "All statements"

Make that "All Ownership-or-control statements" and it's great :-)
