### ISSUE TITLE
Custom validation checks: produce test data

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#99]
Add test data to tickets specifying new checks. Put them in the Ready column

Add new tickets with test data for existing checks. Put them in the Ready column

Work can be tracked on the [BODS validation specification sheet](https://docs.google.com/spreadsheets/d/1KTHGSb_ZkCLB9QpjQ891Y_RxvlBJHFEITjOxptaOTAQ/edit?pli=1&gid=220139423#gid=220139423)

**Comment by kathryn-ods** [comment]
@kd-ods can we close this or is there more to do?
